version: '3.8'

services:
 database:
   image: mysql:latest
   container_name: mysql_db
   environment:
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_DATABASE: ahorro_app
   volumes:
     - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
   ports:
    - "3306:3306"
   networks:
    - database-network

 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database  # Nombre del servicio del contenedor de MySQL al que phpMyAdmin se conectará
      PMA_USER: root          # Usuario de MySQL
      PMA_PASSWORD: 1234  # Contraseña de MySQL
      PMA_ARBITRARY: 1        # Habilitar la opción de introducir cualquier valor en el campo de servidor
    networks:
     - database-network

networks:
  database-network:
    driver: bridge
